docker_image = "golang:1.13"
docker_volume = "muss_go_mods"

def drun(cmd) {
  sh """
    docker run \
      -v ${docker_volume}:/go -v "\$WORKSPACE:/mnt:ro" -w /mnt \
      -e GOPRIVATE -e GO111MODULE \
      --rm ${docker_image} ${cmd}
  """
}
def go(cmd) {
  drun("go ${cmd} ./...")
}

pipeline {
  agent {
    label "bridge-docker"
  }
  options {
    ansiColor('xterm')
  }
  environment {
    GOPRIVATE = 'gerrit.instructure.com'
  }
  stages {
    stage('Build') {
      steps {
        sh """docker pull ${docker_image}"""
        go("build")
      }
    }

    stage('Tests') {
      parallel {
        stage('Test') {
          steps {
            drun("make test")
          }
        }
        stage('Vet') {
          steps {
            go("vet")
          }
        }
      }
    }
  }
  post {
    always {
      sh """
        docker volume rm ${docker_volume}
      """
    }
  }
}
