#!/bin/sh

test -t 0 || echo no tty

name="$1"
shift

loop () {
  i=0
  while true; do
    i=$((i+1))
    printf "# %s - %05d #\n" "$name" "$i"
    timeout=1
    if [ "$name" = "work" ]; then
      timeout=2
    fi
    sleep $timeout
  done
}

if test -t 0; then
  loop &

  while read -r; do
    echo "$name > $REPLY"
    sleep 1
  done
else
  loop
fi
